/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.Admin;
import model.Person;

/**
 *
 * @author josie
 */
public class AdminJPanel extends javax.swing.JPanel {
//
    private JPanel processContainer;
    private Admin admin;
    /**
     * Creates new form AdminJPanel
     */
    AdminJPanel(JPanel processContainer, Admin admin) {
       initComponents();
       this.processContainer = processContainer;
       this.admin = admin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnListOfPersons = new javax.swing.JButton();
        btnAddNewPerson = new javax.swing.JButton();

        btnListOfPersons.setBackground(new java.awt.Color(204, 204, 204));
        btnListOfPersons.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnListOfPersons.setText("List & Search & Create");
        btnListOfPersons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListOfPersonsActionPerformed(evt);
            }
        });

        btnAddNewPerson.setBackground(new java.awt.Color(204, 204, 204));
        btnAddNewPerson.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnAddNewPerson.setText("Add new person");
        btnAddNewPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewPersonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddNewPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListOfPersons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(220, 590, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(btnAddNewPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnListOfPersons, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(420, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAddNewPerson, btnListOfPersons});

    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewPersonActionPerformed
        // TODO add your handling code here:
        AddNewPersonJPanel panel = new AddNewPersonJPanel(processContainer, admin);
        processContainer.add("AddNewPersonJPanel", panel);
        CardLayout layout = (CardLayout) processContainer.getLayout();
        layout.next(processContainer);
        
    }//GEN-LAST:event_btnAddNewPersonActionPerformed

    private void btnListOfPersonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListOfPersonsActionPerformed
        // TODO add your handling code here:
        ListSearchCreateJPanel panel = new ListSearchCreateJPanel(processContainer, admin);
        processContainer.add("ListOfPersonsJPanel", panel);
        CardLayout layout = (CardLayout) processContainer.getLayout();
        layout.next(processContainer);
    }//GEN-LAST:event_btnListOfPersonsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewPerson;
    private javax.swing.JButton btnListOfPersons;
    // End of variables declaration//GEN-END:variables
}
